version: '3.8'

services:
  web:
    build: .
    container_name: devops-web
    ports:
      - "80:80"
    restart: always

  database:
    image: mysql:5.7
    container_name: devops-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    ports:
      - "3306:3306"
    restart: always